[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate/=lib/solmate/src/',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },#read access to the broadcast folder
    { access = "read", path = "./reports" },#read access to the reports folder
]

[fuzz]
runs = 256

private_key = "${PRIVATE_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
